Adding custom join messages.
CircuitSacul/mCoding-Bot pull request #19
Opened 2021-07-23 23:35 UTC by Drakomire

MCoding bot will say a custom join message when a user joins the server. Join Messages need to be disabled on the server before this is in production or two messages will send when someone joins.
**Needed Environment Variables**
WELCOME_CHANNEL=Channel ID

Custom join messages are stored in `assets/join_messages`. If the location is changed it also needs to be changed in `app/config.py`.  Theres only one rn so hopefully some people think of a few more.

2021-07-24 00:52 UTC, Endercheif requested changes
hate to be that guy but just some formatting things.

2021-07-24 00:52 UTC, Endercheif commented on app/bot.py
> +    async def on_member_join(self,member: discord.Member):
Change function to 
`async def on_member_join(self, member: discord.Member):` 
(notice space between `self,` and `member`

2021-07-24 00:52 UTC, Endercheif commented on app/bot.py
> +        await message.add_reaction( "👋")
remove extra space and change to `await message.add_reaction("👋")`

2021-07-26 11:08 UTC, trag1c requested changes

2021-07-26 11:08 UTC, trag1c commented on app/config.py
> +        self.join_messages = open("assets/join_messages").read().strip().split("\n")
Change `.split("\n")` to `.splitlines()`, [here's why.](https://stackoverflow.com/a/22233816)

2021-07-26 16:24 UTC, trag1c requested changes
@Endercheif suggestions at `bot.py:179` & `bot.py:192`

2021-08-06 01:11 UTC, trag1c approved these changes

2021-08-06 01:13 UTC, merged